### PR TITLE
data-backed unary operator selection (v4)

### PR DESCRIPTION
**Pull request by xloem**
Does this look right to you?

I noticed the unary operators were hardcoded, so pulled them out so more could be added if needed.  (A useful unary operator is for example to extract the value of single-element arrays.)

A more powerful solution could be to use an operator dataclass, although this would increase the unmerged changes further.

### CODE REVIEW

**Comment by xloem** [comment]
Note: the operator code could possibly be simplified away entirely into a call to python’s expression `eval` function.

**Comment by Poeloe** [comment]
Hi @xloem, thanks for your contribution!
I will have a look at the code as soon as possible and will get back to you. Stay tuned 😉 

PS: don't forget to agree to the CLA

**Comment by xloem** [comment]
Been a long time since I’ve seen a CLA. It saddens me that the license was changed from AGPL to Apache without comment or explanation in 2022.
@DissectBot agree [company="{default}"]

**Review by Poeloe — APPROVED** [review]
Code looks good, thanks for you addition. I will merge it soon.

**About the `eval` suggestion:** 
We decided to use a "safer" expression evaluation, since `eval` has its own set of security pitfalls. Something like `ast.literal_eval` (https://docs.python.org/3/library/ast.html#ast.literal_eval) would be preferred, but that also comes with its own restrictions and pitfalls.

If you happen to have any further suggestions on this topic, we're more than happy to hear them!

**Comment by xloem** [comment]
Thanks for the merge !

> **About the `eval` suggestion:** We decided to use a "safer" expression evaluation, since `eval` has its own set of security pitfalls. Something like `ast.literal_eval` (https://docs.python.org/3/library/ast.html#ast.literal_eval) would be preferred, but that also comes with its own restrictions and pitfalls.
> 
> If you happen to have any further suggestions on this topic, we're more than happy to hear them!

If a symbolic algebra system were used for expressions here it might pave the way for automatically backsolving to derive some field values like array lengths when writing.

**Pull request merged**
